### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by droserasprout** [kleinmann-orm/kleinmann-orm#2]
## 0.0.1

- [ ] #1 
- [ ] Configure GitHub Actions
- [ ] Test with DipDup
- [ ] Publish on PyPi
